#!/bin/sh

#set -o errexit

## MUST HAVE Git installed to use this script
username=$(git config user.name)
echo Input repo name to clone:
read repo
git clone https://github.com/"$username"/"$repo".git/
sleep 5
clear
echo "$repo" successfully cloned!
echo
ls -I "$repo"; ls -d "$repo" --color=auto
echo
echo
